project:
  type: website

website:
  title: "jumper"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme:
      - journal
      - brand
    css: styles.css



