project:
  type: website
  output-dir: docs

website:
  title: "jumper"
  navbar:
    right:
      - text: "projects"
        href: projects.qmd
      - text: "publications"
        href: publications.qmd
      - text: "blog"
        href: blog.qmd
      - icon: github
        href: https://github.com/JumperAMC
      - icon: linkedin
        href: https://www.linkedin.com/in/andy-collins-27946734/
format:
  html:
    theme:
      - journal
      - brand
    css: styles.css



