project:
  type: website

website:
  title: "jumper"
  navbar:
    right:
      - blog.qmd
      - icon: github
        href: https://github.com/JumperAMC
      - icon: linkedin
        href: https://www.linkedin.com/in/andy-collins-27946734/
format:
  html:
    theme:
      - journal
      - brand
    css: styles.css



